name = "garden"
author = "broccolai"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d4133c23adcb3203a087d56631ea6610c282e06811c1c39217eec53c12046fe"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
