name = "garden"
author = "broccolai"
version = "5.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f47dff24d40ab9412938372e06f748e436eab12e2d6d58f05c38ae7d52a8dd11"

[versions]
fabric = "0.16.13"
minecraft = "1.21.4"
